/**
 * Created by Levana.Xue on 8/21/2015.
 */
Ext.define('SenchaTouchDemo.store.Sessioninfo',{
    extend:'Ext.data.Store',
    requires:[
        'SenchaTouchDemo.model.Sessioninfo'
    ],
    config:{
        storeId:'sessioninfo',
        model:'SenchaTouchDemo.model.Sessioninfo',
        proxy:{
            type:'memory',
            reader:{
                type:'json'
            }
        }
    }
});