/**
 * Created by Levana.Xue on 10/16/2015.
 */
Ext.define('SenchaTouchDemo.store.demo.Stock',{
    extend:'Ext.data.Store',
    requires:[
        'SenchaTouchDemo.model.demo.Stock'
    ],
    config:{
        autoLoad:true,
        storeId:'listDemo',
        model:'SenchaTouchDemo.model.demo.Stock',
        proxy:{
            type:'ajax',
            url:"resources/data/stockInfo.json",
            reader:{
                type:'json'
            }
        }
    }
});