/**
 * Created by Levana.Xue on 8/18/2015.
 */
Ext.define('SenchaTouchDemo.model.OrderType',{
    extend:'Ext.data.Model',
    requires:[
    ],
    config:{
        identifier:{
            type:'sequential',
            prefix:'ot_',
            seed:1000
        },
        fields:[
            {name:'GTD',type:'string'},
            {name:'OrdType',type:'string'},
            {name:'OrdTypeName'}
        ]/*,
        associations:[{
            type:'hasMany',
            name:'OrdTypeNames',
            model:'SenchaTouchDemo.model.OrderTypeName',
            autoLoad: true,
            associationKey:'OrdTypeName'
        }]*/,
        hasMany:[{
            model:'SenchaTouchDemo.model.OrderTypeName',
            name:'OrdTypeName'
        }]
    }
});
